pipeline {
    agent {
        docker {
            image 'node:lts-alpine' 
            args '-p 3000:3000' 
        }
    }
    stages {
        stage('Build') { 
            steps {
                sh 'pwd'
                sh 'whoami'
                sh 'uname -a'
                sh 'npm install' 
            }
        }
    }
}
