pipeline {
    agent {
        docker {
            image 'node:lts-alpine' 
            args '-p 3000:3000 -u 0:0' 
        }
    }  
    stages {
        stage('Build') { 
            steps {    
                sh 'set'            
                sh 'npm install' 
            }
        }
         stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
                input message: 'Finished using the web site? (Click "Proceed" to continue)'
                sh './jenkins/scripts/kill.sh'
            }
        }
    }
}
